# Generated by Django 4.2.1 on 2023-05-10 23:20

import apps.orders.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(help_text='Requester Name', max_length=100, verbose_name='Contact Name')),
                ('contact_phone', models.CharField(help_text='Requester number', max_length=32, validators=[apps.orders.validators.phone_validator], verbose_name='Contact Number')),
                ('agency', models.CharField(editable=False, max_length=150, verbose_name='Agency')),
                ('order_description', models.TextField()),
                ('company', models.CharField(help_text='Provider service company', max_length=100, verbose_name='Company')),
                ('deadline', models.DateTimeField(help_text='Limit date', verbose_name='DeadLine')),
                ('order_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='categories.categories', to_field='name')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['contact_name', 'agency', 'company'], name='orders_orde_contact_9d17f2_idx')],
            },
        ),
    ]
