version: '3.7'

services:
  db:
    image: postgres
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - .dbdata:/var/lib/postgres

  backend:
    build: .
    env_file: .env
    command:
      bash -c '
      while !</dev/tcp/db/5432; do sleep 1; 
      done;
      python manage.py runserver 0.0.0.0:8000'
    
    ports:
      - 8000:8000
    volumes:
      - .:/code
    depends_on:
      - db

